services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NAMA: "Nisa Aprilia
        NIM: "251572010042"
        PRODI: "Sistem Informasi"
        KAMPUS: "STMK Tazkia"
        MINAT: "Cloud Computing dan Web Development"
        ALASAN: "Saya memilih bidang IT karena ingin membuat game yang bisa digunakan diseluruh dunia."
        CITA: "Saya ingin menjadi desainer membuat aplikasi."
    ports:
      - "8085:80"
